<?php
    /** @var $this Sarus_SsoIdp_Block_Login */
?>
<div class="login-form">

    <h1><?php echo $this->__('Login Form') ?></h1>

    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <form action="<?php echo $this->getUrl('*/*/loginPost', ['_secure' => true]) ?>" method="post">
        <?php echo $this->getBlockHtml('formkey') ?>
        <div>
            <label for="username" class="control-label"><?php echo $this->__('Username') ?></label>
            <input type="text" name="login[username]" class="form-control" id="username" placeholder="Your Email">
        </div>
        <div>
            <label for="password" class="control-label"><?php echo $this->__('Password') ?></label>
            <input type="password" name="login[password]" class="form-control" id="password">
        </div>

        <div>
            <a class="forgot-password" href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>"><?php echo $this->__('Forgot your password?') ?></a>
        </div>

        <?php if ($this->getAuthnId()): ?>
            <input type="hidden" name="authn_id" value="<?php echo $this->escapeHtml($this->getAuthnId()) ?>">
        <?php endif; ?>

        <div>
            <button type="submit" class="btn button btn-primary"><?php echo $this->__('Sign In') ?></button>
        </div>
    </form>
</div>

<style>
<?php
// TODO Move to css file
// We'll hold our styles with a heredoc so we can minify them below
$styles=<<<STYLE
html,
body {
	height: 100%;
	background-color: #e7e7e7;
}

.login-form {
	position: relative;
	top: 25%;
	overflow: auto;

	margin: 0 auto;
	padding: 2em;
	max-width: 22em;

	background: #fff;
}
@media (min-width: 310px) {
	.login-form {
		border-radius: 5px;
	}
}
@media (max-height: 700px) {
	.login-form {
		top: 13%;
	}
}
@media (max-height: 550px) {
	.login-form {
		top: 3%;
	}
}
h1 {
	margin: 0 0 2em;
	text-transform: uppercase;
	text-align: center;
	font-size: 1.1em;
}
img {
	display: block;
	margin: 0 auto;
	max-width: 90%;
}

.alert {
	margin: 1em 0 -1.5em;
}

form {
	margin-top: 2.5em;
}
label {
	font-size: 0.9em;
	margin-bottom: 0;
}
.form-control {
	color: #404040;
}
#username {
	margin-bottom: 0.5em;
}
#password {
	margin-bottom: 0.5em;
}
a.forgot-password {
	display: block;
	margin-bottom: 2.5em;
	text-align: center;
}
button {
	width: 100%;
}
.support {
	color: #888;
	font-size: 0.9em;
	line-height: 1.6;
	margin-top: 2.5em;
	text-align: center;
}
.support a {
	color: #666;
}
.support a:hover,
.support a:focus {
	text-decoration: underline;
}
STYLE;

$styles = str_replace(': ', ':', $styles);
$styles = str_replace(' {', '{', $styles);
$styles = str_replace(["\r\n", "\r", "\n", "\t"], '', $styles);
echo $styles;
?>
</style>
