<?php

/** @var $this Sarus_Sarus_Block_Courses */

$customerCourses = $this->getCustomerCourses();
?>
<ul class="sarus-course-listing">
    <?php if (empty($customerCourses)): ?>
        <li><?php echo $this->__('No courses available.') ?></li>
    <?php else: ?>
        <?php foreach ($customerCourses as $courseData): ?>
            <li>
                <h4><?php echo $this->escapeHtml($courseData['title']) ?></h4>

                <img src="<?php echo $this->getCourseImageUrl($courseData) ?>" />

                <?php if (!empty($courseData['description'])): ?>
                    <div class="sarus-course-description">
                        <p><?php echo $courseData['description'] ?></p>
                    </div>
                <?php endif; ?>

                <?php if (!empty($courseData['url'])): ?>
                    <div class="sarus-course-action">
                        <a class="btn" target="_blank" href="<?php echo $courseData['url'] ?>"><?php echo $this->__('Launch Course &raquo;') ?></a>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
<div class="buttons-set">
    <p class="back-link">
        <a href="<?php echo $this->getUrl('customer/account/'); ?>"><small>&#171;</small> <?php echo $this->__('Back') ?></a>
    </p>
</div>

<!-- Sarus course listing CSS -->
<style>
    .sarus-course-listing {
        width: 100%;
    }

    .sarus-course-listing li {
        text-align: center;
        margin-bottom: 1em;
        padding: 0 1em;
        background-color: #f1f1f1;
        overflow: auto;
        margin-right: 10px;
        float: left;
        display: block;
    }
    .sarus-course-listing li h4 {
        font-size: 20px;
        font-weight: 400;
        min-height: 2.1em;
    }
    .sarus-course-listing li img {
        margin: 0 auto;
        max-width: 100%;
        max-height: 200px;
    }
    .sarus-course-listing li .sarus-course-description {
        max-height: 200px;
        overflow: scroll;
        display: none;
    }
    .sarus-course-listing li a {
        display: inline-block;
        text-decoration: none;
        margin: 1em 0;
    }
    .sarus-sarus-list-index div.buttons-set {
        clear: left;
    }
    .sarus-course-listing li .alert-archived {
        margin: 30px 0 0;
    }
    .sarus-course-listing li .alert-archived a {
        margin: 0;
    }
    .sarus-course-listing .btn {
        margin-top: 10px;
        background-color: #666;
        color: white;
    }
    .sarus-course-listing .btn:hover {
        margin-top: 10px;
        background-color: #888;
        color: white;
    }

    @media (max-width: 767px) {
        .sarus-course-listing li {
            min-height: 27em;
            min-width: 100%;
        }
    }
    @media (min-width: 768px) {
        .sarus-course-listing li {
            min-height: 27em;
            min-width: 48%;
        }
    }
    @media (min-width: 992px) {
        .sarus-course-listing li {
            min-height: 26em;
            min-width: 30%;
        }
    }
    @media (min-width: 1260px) {
        .sarus-course-listing li {
            min-height: 23em;
            min-width: 22%;
        }
    }
</style>
