<?php

/** @var $this Sarus_Sarus_Block_Courses */

$customerCourses = $this->getCustomerCourses();
?>
<ul>
    <?php if (empty($customerCourses)): ?>
        <li><?php echo $this->__('No courses available.') ?></li>
    <?php else: ?>
        <?php foreach ($customerCourses as $courseData): ?>
            <li>
                <h4><?php echo $this->escapeHtml($courseData['title']) ?></h4>

                <img src="<?php echo $this->getCourseImageUrl($courseData) ?>" />

                <?php if (!empty($courseData['description'])): ?>
                    <p><?php echo $courseData['description'] ?></p>
                <?php endif; ?>

                <?php if (!empty($courseData['url'])): ?>
                    <div>
                        <a class="btn" target="_blank" href="<?php echo $courseData['url'] ?>"><?php echo $this->__('Go to Course!') ?></a>
                    </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
</ul>
<div class="buttons-set">
    <p class="back-link">
        <a href="<?php echo $this->getUrl('customer/account/'); ?>"><small>&#171;</small> <?php echo $this->__('Back') ?></a>
    </p>
</div>

<!-- TODO Update css classes and styling -->
<style>
    .my-account .item {
        text-align: center;
        margin-bottom: 1em;
    }
    .my-account .item h3 {
        font-size: 20px;
        font-weight: 400;
        min-height: 2.1em;
    }
    .my-account .item img {
        margin: 0 auto;
    }
    .my-account .item a {
        display: inline-block;
        text-decoration: none;
        margin: 1em 0;
    }
    .my-account .item .alert-archived {
        margin: 30px 0 0;
    }
    .my-account .item .alert-archived a {
        margin: 0;
    }
    .my-account .item-inner {
        padding: 0 1em;
        background-color: #f1f1f1;
        overflow: auto;
    }

    @media (min-width: 768px) {
        .my-account .item-inner {
            min-height: 27em;
        }
    }
    @media (min-width: 992px) {
        .my-account .item-inner {
            min-height: 26em;
        }
    }
    @media (min-width: 1260px) {
        .my-account .item-inner {
            min-height: 23em;
        }
    }
</style>
