<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>


<?php if ($_product->getCourseTime()): ?>
<ul class="course-details">
    <li><b>Date: </b><?php echo $_product->getCourseStartDate() . ($_product->getCourseEndDate() && $_product->getCourseEndDate() != $_product->getCourseStartDate() ? ' to ' . $_product->getCourseEndDate() : ''); ?></li>
    <li><b>Time: </b><?php echo $_product->getCourseTime(); ?></li>
    <li><b>Location: </b><?php echo $_product->getCourseState() . ' - ' . $_product->getCourseCity(); ?></li>
    <?php echo ($_product->getCourseMinimumRegistration() ? '<li><b>Minimum Registration:</b> ' . $_product->getCourseMinimumRegistration() . '</li>' : ''); ?>
    <?php echo (!empty($_product->getCourseSeatsAvailable()) ? '<li><b>Seats Available:</b> ' . $_product->getCourseSeatsAvailable() . '</li>' : ''); ?>
</ul>
<?php endif;?>
<div class="facilitators">
    <div class="facilitator">
        <img src="<?php echo $this->getSkinUrl() ?>images/facilitator/clifton.png" alt="Clifton Hall">
        <div class="content">
            <div class="name">Clifton Hall</div>
            <div class="role">Facilitator</div>
        </div>
    </div>
    <div class="facilitator">
        <img src="<?php echo $this->getSkinUrl() ?>images/facilitator/sue.jpg" alt="Sue Hoffman">
        <div class="content">
            <div class="name">Sue Hoffman</div>
            <div class="role">Facilitator</div>
        </div>
    </div>
</div>

<?php echo $this->getChildHtml('product_type_data_extra') ?>