<?php

/** @var $this Swarming_Sarus_Block_Courses */

$customerCourses = $this->getCustomerCourses();
?>
<!-- TODO Update css classes and styling -->
<div class="my-account">
    <div class="page-title">
        <h1><?php echo $this->__('My Courses') ?></h1>
    </div>
    <div ng-app="BrainMD">
        <?php if (!empty($customerCourses)): ?>
            <ul class="row">
                <?php foreach ($customerCourses as $course): ?>
                    <?php if (empty($course['course_uuid'])): continue; endif;?>

                    <li class="item col-sm-6 col-lg-4" ng-repeat="item in ctrl.purchases">
                        <div class="item-inner">
                            <h3><?php echo $this->escapeHtml($course['title']) ?></h3>
                            <img class="img-responsive" src="<?php echo $this->getCourseImageUrl($course); ?>" />
                            <a class="btn" target="_blank" href="<?php echo $this->getCourseLink($course) ?>"><?php echo $this->__('Go to Course!') ?></a>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <p><?php echo $this->__('No courses available.') ?></p>
        <?php endif; ?>
    </div>
</div>
<div class="buttons-set">
    <p class="back-link">
        <a href="<?php echo Mage::getUrl('customer/account/'); ?>"><small>&#171;</small> <?php echo $this->__('Back') ?></a>
    </p>
</div>

<style>
    .my-account .item {
        text-align: center;
        margin-bottom: 1em;
    }
    .my-account .item h3 {
        font-size: 20px;
        font-weight: 400;
        min-height: 2.1em;
    }
    .my-account .item img {
        margin: 0 auto;
    }
    .my-account .item a {
        display: inline-block;
        text-decoration: none;
        margin: 1em 0;
    }
    .my-account .item .alert-archived {
        margin: 30px 0 0;
    }
    .my-account .item .alert-archived a {
        margin: 0;
    }
    .my-account .item-inner {
        padding: 0 1em;
        background-color: #f1f1f1;
        overflow: auto;
    }

    @media (min-width: 768px) {
        .my-account .item-inner {
            min-height: 27em;
        }
    }
    @media (min-width: 992px) {
        .my-account .item-inner {
            min-height: 26em;
        }
    }
    @media (min-width: 1260px) {
        .my-account .item-inner {
            min-height: 23em;
        }
    }
</style>
